package com.everything.JDBC.h2;

import java.sql.Date;

/**
 * Created by mcalancea on 2016-02-16.
 */
public class Functions{
    StringBuilder createDateUnitTable = new StringBuilder();
    CREATE SEQUENCE SEQ_DATEUNIT;
    CREATE TABLE DATEUNIT(
            ID BIGINT DEFAULT SEQ_DATEUNIT.NEXTVAL,
            UNITTIMESTAMP DATE NOT NULL,
            UNITYEAR INT NOT NULL,
            UNITMONTHOFYEAR INT NOT NULL,
            UNITMONTH INT NOT NULL,
            UNITWEEKOFYEAR INT NOT NULL,
            UNITWEEK INT NOT NULL,
            UNITDATE INT NOT NULL,
            UNITDAYOFWEEK INT NOT NULL,
            WEEKDAY INT NOT NULL,
            T_CREATEDON TIMESTAMP,
            T_UPDATEDON TIMESTAMP AS NOW(),
    PRIMARY KEY(ID,UNITTIMESTAMP),
    );
    CREATE INDEX IDXUNITYEAR ON DATEUNIT(UNITYEAR);
    CREATE INDEX IDXUNITMONTHOFYEAR ON DATEUNIT(UNITMONTHOFYEAR);
    CREATE INDEX IDXUNITMONTH ON DATEUNIT(UNITMONTH);
    CREATE INDEX IDXUNITWEEKOFYEAR ON DATEUNIT(UNITWEEKOFYEAR);
    CREATE INDEX IDXUNITWEEK ON DATEUNIT(UNITWEEK);
    CREATE INDEX IDXUNITDATE ON DATEUNIT(UNITDATE);
    CREATE INDEX IDXUNITDAYOFWEEK ON DATEUNIT(UNITDAYOFWEEK);
    CREATE INDEX IDXWEEKDAY ON DATEUNIT(WEEKDAY);

    public static Long insertSelectDate(Date date) {
        return new BigInteger(String.valueOf(value)).isProbablePrime(100);
    }
}
